### ISSUE TITLE
AppCode compatibility?

### ISSUE THREAD

**Issue by dxclancy** [facebook/chisel#124]
Is this intended to work/already works in AppCode? 

I've installed as per the instructions and have chisel commands (pviews, visualize, etc...) working in Xcode.

Issuing "help" in lldb within AppCode displays the chisel commands.  However, I don't see any results in AppCode from issuing commands (pviews, visualize, etc...) .  Other non-chisel commands, even 3rd party additions, work.

I generally assume issues like these are my own fault somehow, but it would be reassuring to know if these commands work for others within AppCode.

Thanks!

**Comment by kastiglione** [comment]
This sounds familiar to #12. I wonder if those underlying issues were resolved, and if so if there's been any regressions.

**Comment by dxclancy** [comment]
I did see #12 before commenting but it wasn't clear to me whether #12 only effects printouts?  For instance, <visualize> does not launch theUIImage into preview for me either.

**Comment by kastiglione** [comment]
Good point, sorry I was too quick to answer. In the past I used AppCode a bit, but not lately. Have you filed a ticket with JetBrains?

**Comment by kastiglione** [comment]
To answer your first sentence, Chisel isn't intended to be Xcode only, and so should work in AppCode. However I'm not aware of any contributors who use AppCode, so I'd have to unfortunately call AppCode unsupported.

**Comment by kastiglione** [comment]
@dxclancy I'm going to close this because I don't use AppCode and don't have the time to investigate this. I am curious to hear more if you have any updates. Hopefully any issues can be resolved by the folks at JetBrains.

**Comment by dxclancy** [comment]
Here is the [JetBrains AppCode issue](https://youtrack.jetbrains.com/issue/OC-9356)

**Comment by kastiglione** [comment]
Thanks for the update @dxclancy. I'll follow up with something to see whether it's running or not, or if it's just an output issue.

**Comment by kastiglione** [comment]
> It is not limited to printing. "visualize" also does nothing. I don't think the commands are getting to the chisel code?

@dxclancy You can turn on lldb logging to observe what actions are, or are not, taking place when you run chisel commands. The base command is `log enable lldb <category>`, and some categories that are applicable here are `api`, `commands`, and `script`. So for example try:

```
(lldb) log enable lldb api commands script
```

then run some chisel commands, like `visualize`.

**Comment by dxclancy** [comment]
`(lldb) log enable lldb api commands script` 
has no visual effect in AppCode, whereas when I do it in Xcode I get a spew of logging.

**Comment by dxclancy** [comment]
btw, just as a datapoint, I also have a [quick look command ](https://github.com/ryanolsonk/LLDB-QuickLook)  which is a python script and it does run in AppCode.

**Comment by kastiglione** [comment]
> has no visual effect in AppCode

This sounds like a bug. I wonder if the lack of output for the logs has anything to do with the lack of output for chisel commands.

**Comment by kastiglione** [comment]
> just as a datapoint, I also have a [quick look command](https://github.com/ryanolsonk/LLDB-QuickLook) which is a python script and it does run in AppCode

Thanks! I wonder if chisel should stop using `print` directly. Chisel's commands call `print` liberally all over the place, and none of the commands use the `result` argument supplied by lldb when invoking the python entry point. However, this doesn't really explain why `visualize` doesn't work.

**Comment by kastiglione** [comment]
If anyone wants to help debug this, here's a gist that has two simple commands `stdio_print` and `result_print`: https://gist.github.com/kastiglione/c5a27e39f1dda34cce4f17c6545b59c6

If both commands successfully print inside AppCode, I can probably come up with another test or two.

**Comment by dxclancy** [comment]
Looks like stdio_print doesn't work in AppCode.
```
(lldb) stdio_print
(lldb) result_print
Printing via result
```

**Comment by kastiglione** [comment]
Which version of Xcode? In Xcode 7.3.0, stdio in python scripts was broken, but it's fixed in 7.3.1.

In any case, it seems we know at least one major reason why chisel commands don't work in AppCode. And it's fixable on our end even if JetBrains can't prioritize the problem. Maybe they just need to be let known exactly what the issue is, maybe it's a simple fix.

**Comment by dvanoni** [comment]
Just wanted to see if any progress had been made on this issue. I'm still encountering it on the following setup:
- Chisel 1.5.0
- AppCode 2016.3.1

It appears to be working in Xcode 8.2.1

Thanks!

**Comment by jay3005** [comment]
Np

**Comment by NikolaiSa** [comment]
fwiw, it looks like the visualize command *does* save the image into the tmp/xcode_debug_images folder when used in AppCode, so at least there's a way to access it. Not as elegant but at least possible.

**Comment by kastiglione** [comment]
https://youtrack.jetbrains.com/issue/OC-9356 has been marked as fixed.
