### ISSUE TITLE
Xcode11 error: module importing failed: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by ceekay1991** [facebook/chisel#272]
error: 'pviews' is not a valid command.
error: module importing failed: Missing parentheses in call to 'print'. Did you mean print('Whoops! You are missing the <' + arg.argName + '> argument.')? (fblldb.py, line 98)
  File "temp.py", line 1, in <module>

**Comment by danielpetroianu** [comment]
I experience the same error message when running with Xcode 11. 
I think this is related to https://github.com/facebook/chisel/issues/262

**Comment by spnkr** [comment]
you're using python 3, which doesn't work with chisel. the python binary xcode 11 uses is here fwiw: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework

**Comment by TomLongJoy** [comment]
cd ~/Downloads && git clone https://github.com/chenjiangchuan/chisel.git && cd chisel &&cp -f -R -v libexec /usr/local/Cellar/chisel/1.8.1
I use this , my chisel work.

**Comment by kolinkrewinkel** [comment]
Should be fixed with #266!

**Comment by monologue555** [comment]
Use `brew install chisel` (1.8.1) not work, because merge #266! not update to brew repo. So I download master code to fix this issue.

**Comment by mattjankowiak** [comment]
Still seeing this issue with Chisel 1.8.1.  Any chance we can get the brew repo updated with the changes from #266 ?  Been using Chisel for many years and I love it. Thanks for all your hard work!

**Comment by raytso** [comment]
Still seeing this with 1.8.1.

**Comment by hvsw** [comment]
Same issue here

**Comment by sxiaojian88** [comment]
Still seeing this with 1.8.1.

**Comment by Ronaldoh1** [comment]
same

**Comment by nikunjinexture** [comment]
Same issue

**Comment by kolinkrewinkel** [comment]
Sorry folks, I've been a neglectful maintainer! 
- Just created 2.0.0 release (https://github.com/facebook/chisel/releases/tag/2.0.0)
- Will put up a PR for Homebrew and link it here.

**Comment by kolinkrewinkel** [comment]
Should be good to go now with a `brew upgrade`. Let us know if there are any issues!

**Comment by yayang** [comment]
> cd ~/Downloads && git clone https://github.com/chenjiangchuan/chisel.git && cd chisel &&cp -f -R -v libexec /usr/local/Cellar/chisel/1.8.1
> I use this , my chisel work.

worked for me, thanks
