### ISSUE TITLE
chisel load failed

### ISSUE THREAD

**Issue by BlankConan** [facebook/chisel#278]
macOS 10.14.5 (18F132)
Xcode Version 11.1 (11A1027)
Python 3.7.3
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

error: module importing failed: Missing parentheses in call to 'print'. Did you mean print('Whoops! You are missing the <' + arg.argName + '> argument.')? (fblldb.py, line 98)

**Comment by ansonj** [comment]
I believe this was resolved by pull request #266. Issue #274 tracks a suggestion for the maintainers to make a new release, which would distribute this fix.

**Comment by raytso** [comment]
Can confirm this issue. Still seeing the same error.

macOS 10.14.6
Xcode Version 11.2.1

**Comment by archmagees** [comment]
Same issue.

macOS  10.15.1
Xcode 11.1

**Comment by BlankConan** [comment]
> Can confirm this issue. Still seeing the same error.
> 
> macOS 10.14.6
> Xcode Version 11.2.1

error messages:

error: module importing failed: Missing parentheses in call to 'print'. Did you mean print('Whoops! You are missing the <' + arg.argName + '> argument.')? (fblldb.py, line 98)
  File "temp.py", line 1, in <module>

**Comment by BlankConan** [comment]
@raytso 
error: module importing failed: Missing parentheses in call to 'print'. Did you mean print('Whoops! You are missing the <' + arg.argName + '> argument.')? (fblldb.py, line 98)
  File "temp.py", line 1, in <module>

**Comment by renanvs** [comment]
Hi, this occurred with too.

Does It some fix to this error?

**Comment by maniramezan** [comment]
Since they release a new version, I manually copied `command` folder and rest of `.py` files in the root of the repo to `/usr/local/opt/chisel/libexec/` and replaced it with the ones installed by `brew`.

**Comment by kolinkrewinkel** [comment]
You should be able to update in a more automated way now with `brew upgrade`. Sorry for the delay!
